apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
build:
  local: # build local image
    push: false #do not push to hub
  # googleCloudBuild:
  #   projectId: effective-tea-276310
  artifacts:
    - image: penio/auth #us.gcr.io/effective-tea-276310/auth #gcoud require that type of naming, this conflicts with docker repo
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.js'
            dest: .
